services:
  # postgres:
  #   image: postgres:16.3
  #   container_name: postgres_container
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: 12345
  #     POSTGRES_DB: testdevgo
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #     - ./init:/docker-entrypoint-initdb.d
  redis:
    image: redis:7.0
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_container
    ports: 
      - "1434:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "duyCC12345@"
    volumes:
      - mssql_data:/var/opt/mssql
  
volumes:
  # postgres_data:
  redis_data:
  mssql_data: